// Build CPAT-AI-Mitigation-MVP_Overview_v1.0.pptx: short pitch + user guide (7 slides), styled like the Excise
// Diagnostic guide and Excise-Fiscal proposal decks (navy / teal / amber, Cambria headings, Calibri body).
// Screenshots: presentation/img/*.png from make_screenshots_v1_0.py (rendered from the real workbook).
//
//   node presentation/build_deck_v1_0.js
const path = require("path");
const pptxgen = require("pptxgenjs");
const { applyTheme } = require(process.env.PPTX_SKILL + "/scripts/apply_theme.js");

const HERE = __dirname;
const IMG = (f) => path.join(HERE, "img", f);
const OUT = path.join(HERE, "CPAT-AI-Mitigation-MVP_Overview_v1.0.pptx");

const THEME = {
  name: "CPAT AI Mitigation",
  headFontFace: "Cambria",
  bodyFontFace: "Calibri",
  colors: {
    dk1: "1F1F2E", lt1: "FFFFFF", dk2: "1E2761", lt2: "F4F6FB",
    accent1: "1E2761", accent2: "0F7B6C", accent3: "E08A1E", accent4: "D4A24C",
    accent5: "5C667A", accent6: "D5DAE3", hlink: "0F7B6C", folHlink: "5C667A",
  },
};
const NAVY = "1E2761", TEAL = "0F7B6C", AMBER = "E08A1E", GOLD = "D4A24C", INK = "1F1F2E", GREY = "5C667A";
const CARD = "F4F6FB", LINE = "D5DAE3", TEAL_T = "EAF4F2", AMBER_T = "FDF3E6", ICE = "CADCFC";

const { imageSize } = require("image-size");
const dim = imageSize(require("fs").readFileSync(IMG("04_formulas.png")));
const IMGH = Math.min(3.3, 12.1 * dim.height / dim.width);     // formula screenshot, aspect ratio kept
const IMGW = IMGH * dim.width / dim.height;
const pres = new pptxgen();
pres.layout = "LAYOUT_WIDE"; // 13.333 x 7.5 in, as the Excise decks
pres.title = "CPAT-AI-Mitigation-MVP v1.00: pitch and user guide";
pres.theme = { headFontFace: THEME.headFontFace, bodyFontFace: THEME.bodyFontFace };

pres.defineSlideMaster({
  title: "TITLE_DARK",
  background: { color: NAVY },
  objects: [
    { placeholder: { options: { name: "title", type: "title", x: 0.6, y: 1.55, w: 6.2, h: 1.6, fontFace: "Cambria",
      fontSize: 40, bold: true, color: "FFFFFF", valign: "top", align: "left", margin: 0 }, text: "" } },
  ],
});
pres.defineSlideMaster({
  title: "CONTENT",
  background: { color: "FFFFFF" },
  objects: [
    { placeholder: { options: { name: "label", type: "body", x: 0.6, y: 0.32, w: 12.1, h: 0.3, fontFace: "Calibri",
      fontSize: 11, bold: true, color: TEAL, charSpacing: 2, margin: 0 }, text: "" } },
    { placeholder: { options: { name: "title", type: "title", x: 0.6, y: 0.62, w: 12.1, h: 0.7, fontFace: "Cambria",
      fontSize: 30, bold: true, color: NAVY, valign: "top", align: "left", margin: 0 }, text: "" } },
    { text: { text: "CPAT-AI-Mitigation-MVP v1.00  ·  pitch and user guide  ·  screenshots from the workbook",
      options: { x: 0.6, y: 7.05, w: 9.5, h: 0.25, fontSize: 9, color: GREY, margin: 0 } } },
  ],
  slideNumber: { x: 12.3, y: 7.05, w: 0.5, h: 0.25, fontSize: 9, color: GREY, align: "right" },
});

let n = 0;
const nm = (s) => `${s}-${++n}`;
function header(slide, label, title) {
  slide.addText(label, { placeholder: "label" });
  slide.addText(title, { placeholder: "title" });
}
function picture(slide, file, x, y, w, h) {
  slide.addShape(pres.shapes.RECTANGLE, { x: x - 0.06, y: y - 0.06, w: w + 0.12, h: h + 0.12, fill: { color: "FFFFFF" },
    line: { color: LINE, width: 1 }, shadow: { type: "outer", color: "1E2761", opacity: 0.18, blur: 6, offset: 2, angle: 90 },
    objectName: nm("frame") });
  slide.addImage({ path: IMG(file), x, y, w, h, objectName: nm("screenshot") });
}
function badge(slide, txt, x, y, color, size = 0.42) {
  slide.addShape(pres.shapes.OVAL, { x, y, w: size, h: size, fill: { color }, line: { color }, objectName: nm("badge") });
  slide.addText(txt, { x, y, w: size, h: size, align: "center", valign: "middle", fontSize: 14, bold: true,
    color: "FFFFFF", margin: 0, isTextBox: true, objectName: nm("badgeText") });
}
function item(slide, num, head, body, x, y, w, color = TEAL, bodySize = 13) {
  badge(slide, String(num), x, y, color);
  slide.addText([
    { text: head, options: { bold: true, fontSize: 15, color: INK, breakLine: true } },
    { text: body, options: { fontSize: bodySize, color: GREY } },
  ], { x: x + 0.6, y: y - 0.05, w: w - 0.6, h: 1.0, valign: "top", margin: 0, isTextBox: true, objectName: nm("item") });
}

// 1. Title -------------------------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "TITLE_DARK" });
  s.addText("PITCH + USER GUIDE", { x: 0.6, y: 1.05, w: 6, h: 0.35, fontSize: 12, bold: true, color: GOLD, charSpacing: 3,
    margin: 0, isTextBox: true, objectName: nm("kicker") });
  s.addText("CPAT-AI-Mitigation-MVP v1.00", { placeholder: "title" });
  s.addText("CPAT's mitigation equations, generated by AI as a tidy Excel workbook that you can copy, drag and "
    + "extend: one tab, scenarios side by side.", { x: 0.6, y: 3.25, w: 5.9, h: 1.2, fontSize: 18, color: ICE,
    valign: "top", margin: 0, isTextBox: true, objectName: nm("subtitle") });
  ["AI-generated", "Copy-pasteable", "Scenarios left to right"].forEach((t, i) => {
    const w = [1.7, 1.85, 2.3][i], x = [0.6, 2.45, 4.45][i];
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y: 4.75, w, h: 0.45, rectRadius: 0.12, fill: { color: "2E3A7A" },
      line: { color: "3A4A8A" }, objectName: nm("chip") });
    s.addText(t, { x, y: 4.75, w, h: 0.45, align: "center", valign: "middle", fontSize: 13, color: "FFFFFF",
      margin: 0, isTextBox: true, objectName: nm("chipText") });
  });
  s.addText("Draft, October 2026  ·  Egypt data  ·  prototype for discussion", { x: 0.6, y: 6.8, w: 6, h: 0.3,
    fontSize: 10, color: ICE, margin: 0, isTextBox: true, objectName: nm("footnote") });
  picture(s, "01_overview.png", 7.15, 1.2, 5.55, 3.88);
  s.addText("The Mitigation tab as it opens: everything rolled up", { x: 7.15, y: 5.2, w: 5.55, h: 0.3, fontSize: 11,
    color: ICE, italic: true, margin: 0, isTextBox: true, objectName: nm("caption") });
  s.addNotes("A one-tab Excel version of the CPAT mitigation chain (policies, prices, fuel use, revenues, CO2), "
    + "generated and checked by AI. The deck is both a short pitch (slides 2-3) and a user guide (slides 4-6).");
}

// 2. Purpose and scope ------------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "CONTENT" });
  header(s, "PURPOSE AND SCOPE", "What this workbook is for");
  item(s, 1, "Show that AI can generate a working Excel model",
    "Every formula, label and check was written by AI from plain-language instructions, and every value is "
    + "re-computed independently to confirm it.", 0.6, 1.75, 6.6);
  item(s, 2, "Do it for the main mitigation equations",
    "Policies → retail prices → fuel use → revenues → CO2, following the CPAT documentation and legacy rules.",
    0.6, 3.15, 6.6);
  item(s, 3, "Make it easier to read than today's CPAT",
    "One tab, numbered sections, one row per fuel, everything rolled up on open. Tidier and more compact.",
    0.6, 4.55, 6.6);
  s.addShape(pres.shapes.RECTANGLE, { x: 7.75, y: 1.65, w: 4.95, h: 3.95, fill: { color: CARD }, line: { color: LINE },
    objectName: nm("card") });
  s.addText([
    { text: "DEFINITION", options: { bold: true, fontSize: 11, color: TEAL, charSpacing: 2, breakLine: true } },
    { text: "A minimum viable product (MVP): the CPAT mitigation module rebuilt as an AI-generated, "
      + "copy-pasteable Excel file.", options: { fontSize: 13, color: INK, breakLine: true } },
    { text: " ", options: { fontSize: 6, breakLine: true } },
    { text: "IN SCOPE", options: { bold: true, fontSize: 11, color: TEAL, charSpacing: 2, breakLine: true } },
    { text: "Egypt; 16 energy-use sectors × 8 fuels; 2022–2040", options: { bullet: true, fontSize: 13, color: INK, breakLine: true } },
    { text: "Carbon tax, ETS, fuel price reform, feebates", options: { bullet: true, fontSize: 13, color: INK, breakLine: true } },
    { text: "Prices, fuel use, revenues and CO2, in real 2026 USD", options: { bullet: true, fontSize: 13, color: INK, breakLine: true } },
    { text: " ", options: { fontSize: 6, breakLine: true } },
    { text: "NOT YET", options: { bold: true, fontSize: 11, color: AMBER, charSpacing: 2, breakLine: true } },
    { text: "Power sector, other gases, local pollutants", options: { bullet: true, fontSize: 13, color: INK, breakLine: true } },
    { text: "Full numerical match with legacy CPAT", options: { bullet: true, fontSize: 13, color: INK } },
  ], { x: 7.95, y: 1.8, w: 4.55, h: 3.7, valign: "top", margin: 0, paraSpaceAfter: 3, isTextBox: true,
    objectName: nm("definition") });
  ["1. Policies", "2. Retail prices", "5-8. Fuel use", "12. Revenues", "13. CO2"].forEach((t, i) => {
    const x = 0.6 + i * 2.46;
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y: 5.95, w: 1.95, h: 0.6, rectRadius: 0.1, fill: { color: NAVY },
      line: { color: NAVY }, objectName: nm("flow") });
    s.addText(t, { x, y: 5.95, w: 1.95, h: 0.6, align: "center", valign: "middle", fontSize: 14, bold: true,
      color: "FFFFFF", margin: 0, isTextBox: true, objectName: nm("flowText") });
    if (i < 4) s.addShape(pres.shapes.RIGHT_ARROW, { x: x + 2.02, y: 6.1, w: 0.37, h: 0.3, fill: { color: GOLD },
      line: { color: GOLD }, objectName: nm("flowArrow") });
  });
  s.addText("The chain on the Mitigation tab (legacy CPAT section numbers)", { x: 0.6, y: 5.6, w: 8, h: 0.3,
    fontSize: 12, italic: true, color: GREY, margin: 0, isTextBox: true, objectName: nm("caption") });
  s.addNotes("Three purposes: (1) demonstrate AI generation of an Excel model; (2) for the core mitigation equations; "
    + "(3) make it more readable than the current workbook. Scope and gaps on the right.");
}

// 3. Problems and fixes -------------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "CONTENT" });
  header(s, "WHAT CHANGES", "Four problems with today's Excel, four fixes");
  s.addText("TODAY IN CPAT", { x: 0.6, y: 1.5, w: 5.2, h: 0.3, fontSize: 11, bold: true, color: AMBER, charSpacing: 2,
    margin: 0, isTextBox: true, objectName: nm("colhead") });
  s.addText("IN THE MVP", { x: 6.7, y: 1.5, w: 6, h: 0.3, fontSize: 11, bold: true, color: TEAL, charSpacing: 2,
    margin: 0, isTextBox: true, objectName: nm("colhead") });
  const rows = [
    ["Messy and hard to read", "Numbered sections, one row per fuel, rolled up on open; differences with legacy listed on one tab"],
    ["Hard to copy when a formula points to a fixed row, e.g. a time series",
      "Years run left to right and scenarios sit side by side, so fixed rows stay fixed: one formula per block"],
    ["Hard to copy when a formula needs a sector- or fuel-specific number",
      "Those numbers sit in a left-hand section (columns D:G), so every row uses the same formula"],
    ["New scenarios are slow to build",
      "Copy a scenario block; it finds its settings with one lookup on its MTInputs column"],
  ];
  rows.forEach(([a, b], i) => {
    const y = 1.9 + i * 1.22;
    s.addShape(pres.shapes.RECTANGLE, { x: 0.6, y, w: 5.2, h: 1.02, fill: { color: AMBER_T }, line: { color: "F2D9B6" },
      objectName: nm("problem") });
    s.addText(a, { x: 0.8, y, w: 4.85, h: 1.02, fontSize: 15, color: INK, valign: "middle", margin: 0, isTextBox: true,
      objectName: nm("problemText") });
    s.addShape(pres.shapes.RIGHT_ARROW, { x: 5.95, y: y + 0.33, w: 0.6, h: 0.36, fill: { color: GOLD }, line: { color: GOLD },
      objectName: nm("arrow") });
    s.addShape(pres.shapes.RECTANGLE, { x: 6.7, y, w: 6.0, h: 1.02, fill: { color: TEAL_T }, line: { color: "C7E3DE" },
      objectName: nm("fix") });
    s.addText(b, { x: 6.9, y, w: 5.65, h: 1.02, fontSize: 15, color: INK, valign: "middle", margin: 0, isTextBox: true,
      objectName: nm("fixText") });
  });
  s.addNotes("Points 3-6 of the brief: readability, fixed rows (time series), sector- and fuel-specific quantities, "
    + "and speed of building scenarios.");
}

// 4. Scenarios left to right -------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "CONTENT" });
  header(s, "USER GUIDE · SCENARIOS", "Scenarios sit side by side: add one in three steps");
  picture(s, "02_scenarios.png", 0.6, 1.55, 12.1, 1.51);
  s.addText("Each scenario is a block of columns: output codes, 2022 (beige), years to 2040, and a blank column.",
    { x: 0.6, y: 3.2, w: 12.1, h: 0.3, fontSize: 12, italic: true, color: GREY, margin: 0, isTextBox: true,
      objectName: nm("caption") });
  item(s, 1, "Copy a settings column", "In MTInputs, copy the last scenario column one to the right and edit it.",
    0.6, 3.8, 5.6, TEAL, 13);
  item(s, 2, "Copy a scenario block", "In Mitigation, copy a whole block and paste it to the right.", 0.6, 4.85, 5.6,
    TEAL, 13);
  item(s, 3, "Done", "The scenario number goes up by one and the block reads its own MTInputs column.", 0.6, 5.9, 5.6,
    TEAL, 13);
  picture(s, "05_mtinputs.png", 6.75, 3.85, 5.95, 1.81);
  s.addText("MTInputs keeps the legacy rows; one column per scenario (red = changed)", { x: 6.75, y: 5.8, w: 5.95,
    h: 0.3, fontSize: 12, italic: true, color: GREY, margin: 0, isTextBox: true, objectName: nm("caption") });
  s.addNotes("Point 6: scenarios via a simple lookup. Row 5 holds the scenario number; every input row looks up its "
    + "value in that MTInputs column. Copying a block increments the number automatically.");
}

// 5. Left section -------------------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "CONTENT" });
  header(s, "USER GUIDE · ROWS", "Sector- and fuel-specific numbers live on the left");
  picture(s, "03_left_section.png", 0.6, 1.55, 7.9, 4.23);
  item(s, "A", "Columns B:C — fuel and sector", "Every row is one fuel in one sector (here: road transport).",
    9.0, 1.65, 3.75, NAVY, 13);
  item(s, "B", "Columns D:G — that row's numbers",
    "Emission factor, elasticities, positions: looked up once from the Inputs sheet.", 9.0, 3.05, 3.75, NAVY, 13);
  item(s, "C", "Year columns — one formula", "The same formula in every row of a block: copy, drag or paste freely.",
    9.0, 4.45, 3.75, NAVY, 13);
  s.addText("Columns B:G and I:K are grouped and rolled up on open: click + above the columns to show them.",
    { x: 0.6, y: 6.15, w: 12.1, h: 0.35, fontSize: 13, color: GREY, margin: 0, isTextBox: true, objectName: nm("tip") });
  s.addNotes("Point 5: equations that need a sector- or fuel-specific quantity read it from the parameter columns of "
    + "their own row, so the formula is identical everywhere.");
}

// 6. Two formula styles -------------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "CONTENT" });
  header(s, "USER GUIDE · FORMULAS", "Two ways to write the same formula");
  picture(s, "04_formulas.png", 0.6 + (12.1 - IMGW) / 2, 1.5, IMGW, IMGH);
  const y0 = 1.5 + IMGH + 0.35, hc = 6.75 - y0;
  s.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: y0, w: 3.85, h: hc, fill: { color: CARD }, line: { color: LINE },
    objectName: nm("card") });
  s.addText([
    { text: "Direct formulas (left)", options: { bold: true, fontSize: 15, color: NAVY, breakLine: true } },
    { text: "Plain Excel arithmetic, readable cell by cell. Data years and projection years are separate blocks.",
      options: { fontSize: 13, color: INK } },
  ], { x: 0.75, y: y0 + 0.1, w: 3.6, h: hc - 0.2, valign: "top", margin: 0, isTextBox: true, objectName: nm("cardText") });
  s.addShape(pres.shapes.RECTANGLE, { x: 4.72, y: y0, w: 3.85, h: hc, fill: { color: "EEECE1" }, line: { color: "D9D4BC" },
    objectName: nm("card") });
  s.addText([
    { text: "LAMBDA formulas (right)", options: { bold: true, fontSize: 15, color: "9C0006", breakLine: true } },
    { text: "Named functions such as FUELUSE(…), defined once in Name Manager, in the light-beige 2040 column. "
      + "They may hold IF conditions.", options: { fontSize: 13, color: INK } },
  ], { x: 4.87, y: y0 + 0.1, w: 3.6, h: hc - 0.2, valign: "top", margin: 0, isTextBox: true, objectName: nm("cardText") });
  s.addShape(pres.shapes.RECTANGLE, { x: 8.85, y: y0, w: 3.85, h: hc, fill: { color: TEAL_T }, line: { color: "C7E3DE" },
    objectName: nm("banner") });
  s.addText([
    { text: "Both can be dragged", options: { bold: true, fontSize: 15, color: TEAL, breakLine: true } },
    { text: "Drag a direct formula right, or copy the LAMBDA left across the whole row: the checks confirm the "
      + "results are identical.", options: { fontSize: 13, color: INK } },
  ], { x: 9.0, y: y0 + 0.1, w: 3.6, h: hc - 0.2, valign: "top", margin: 0, isTextBox: true, objectName: nm("bannerText") });
  s.addNotes("Point 8: direct formulas on the left (2022-2039) and compact LAMBDA formulas on the right (2040). "
    + "Light beige marks blocks that are copy-pasteable within themselves but not into white cells.");
}

// 7. Next steps ---------------------------------------------------------------------------------------------------
{
  const s = pres.addSlide({ masterName: "CONTENT" });
  header(s, "NEXT STEPS", "Next: keep data, charts and scenarios together");
  picture(s, "06_results.png", 0.6, 1.55, 7.4, 1.37);
  s.addText("Results already carry full CPAT codes per scenario, e.g. egy.mit.co2.all.all.2", { x: 0.6, y: 3.1, w: 7.4,
    h: 0.3, fontSize: 12, italic: true, color: GREY, margin: 0, isTextBox: true, objectName: nm("caption") });
  item(s, 1, "Store data, charts and scenario settings in CPAT",
    "Settings already sit in MTInputs columns; add data and charts next to them.", 0.6, 3.75, 7.4, TEAL, 13);
  item(s, 2, "Collect outputs for many scenarios in an updated MTOutputs",
    "Copy results across scenarios by their codes. Inputs stay as they are for now.", 0.6, 4.85, 7.4, TEAL, 13);
  item(s, 3, "Extend and validate", "Power sector, other gases, and a numerical check against legacy CPAT.", 0.6, 5.95,
    7.4, TEAL, 13);
  s.addShape(pres.shapes.RECTANGLE, { x: 8.5, y: 1.5, w: 4.2, h: 5.0, fill: { color: NAVY }, line: { color: NAVY },
    objectName: nm("card") });
  s.addText([
    { text: "GETTING STARTED", options: { bold: true, fontSize: 11, color: GOLD, charSpacing: 2, breakLine: true } },
    { text: "Open the file: the Mitigation tab opens rolled up", options: { bullet: true, breakLine: true } },
    { text: "Buttons 1 / 2 / 3 (top left) open more rows", options: { bullet: true, breakLine: true } },
    { text: "Change a scenario in its MTInputs column", options: { bullet: true, breakLine: true } },
    { text: "ReadMe explains assumptions; LegacyDiff lists every difference with legacy CPAT",
      options: { bullet: true, breakLine: true } },
    { text: "Formulas: Formulas > Name Manager", options: { bullet: true } },
  ], { x: 8.75, y: 1.75, w: 3.75, h: 4.6, fontSize: 15, color: "FFFFFF", valign: "top", margin: 0, paraSpaceAfter: 16,
    isTextBox: true, objectName: nm("start") });
  s.addNotes("Point 7: store data, graphs and scenario settings with CPAT, then copy outputs for many scenarios into "
    + "an updated MTOutputs sheet (outputs only for now, not inputs).");
}

(async () => {
  await pres.writeFile({ fileName: OUT });
  await applyTheme(OUT, THEME);
  console.log("wrote", OUT);
})();
